<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Karaoke | <?= $this->title ?></title>

        <?php $this->section('head') ?>
        <link rel="stylesheet" type="text/css" href="/css/app.css">
        <?php $this->stop() ?>

        <?php if (APPLICATION_ENV != ENV_PRODUCTION) echo $this->debugbar->renderHead(); ?>
    </head>

    <body>
        <?php $this->section('content') ?>
            ...
        <?php $this->stop() ?>

        <?php $this->section('scripts') ?>
            <script src="/js/app.js" type="text/javascript"></script>
        <?php $this->stop() ?>

        <?php if (APPLICATION_ENV != ENV_PRODUCTION) echo $this->debugbar->render(); ?>
    </body>
</html>
