<?php
$artist = $this->artist;
?>

<?php $this->layout('layouts/console', [
    'title' => $artist->name,
]); ?>

<?php $this->section('content') ?>
    <div class="grid-x grid-padding-x margin-bottom">
        <div class="small-12 cell">
            <nav aria-label="You are here:" role="navigation">
                <ul class="breadcrumbs">
                    <li><a href="<?= $this->pathFor('console_home') ?>"><?= $this->translate('home') ?></a></li>
                    <li><a href="<?= $this->pathFor('console_artists') ?>"><?= $this->translate('artists') ?></a></li>
                    <li class="show-for-sr">
                        <span class="show-for-sr">Current: </span> <?= $artist->name ?>
                    </li>
                </ul>
            </nav>

            <h2><?= $artist->name ?></h2>
            <p><?= $artist->getMeta('summary') ?></p>
            <ul class="song-tag-list">
                <?php foreach ($artist->tags()->where('is_valid', 1)->get() as $tag): ?>
                    <li><a href="<?= $this->pathFor('console_tags_view', ['tag_id' => $tag->id]) ?>" class="button"><?= $tag->name ?></a></li>
                <?php endforeach ?>
            </ul>
            <hr>
            <h3>Songs</h3>
            <?= $this->insert('console/partials/songs_list', [
                'songs' => $this->songs,
                // 'include_artist_name' => true,
            ]) ?>
        </div>
    </div>
<?php $this->replace() ?>
