<?php $this->layout('layouts/console', [
    'title' => 'Artists',
    'back_path' => $this->pathFor('console_home'),
]); ?>

<?php $this->section('content') ?>
    <div class="grid-x grid-padding-x">
        <div class="small-12 cell">
            <nav aria-label="You are here:" role="navigation">
                <ul class="breadcrumbs">
                    <li><a href="<?= $this->pathFor('console_home') ?>"><?= $this->translate('home') ?></a></li>
                    <li>
                        <span class="show-for-sr">Current: </span> <?= $this->translate('tags') ?>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="grid-x grid-padding-x margin-y tags-list">
        <?php foreach ($this->tags as $tag): ?>
            <div class="small-4 cell">
                <a href="<?= $this->pathFor('console_tags_view', ['tag_id' => $tag->id]); ?>" class="button expanded large tags-list__item"><?= $tag->name ?></a>
            </div>
        <?php endforeach ?>
    </div>
<?php $this->replace() ?>
