<?php $this->layout('layouts/admin', [
    'title' => 'Update songs',
]); ?>

<?php $this->section('content') ?>
    <div class="grid-x grid-padding-x margin-y">
        <div class="small-12 cell">
            <form action="<?= $this->pathFor('admin_songs_update_post') ?>" method="post">
                <input type="hidden" name="<?= $this->csrf_name ?>" value="<?= $this->csrf_value ?>">
                <button class="button large"><?= $this->translate('update') ?></button>
            </form>
        </div>
    </div>
<?php $this->replace() ?>
