<?php $this->layout('layouts/admin', [
    'title' => 'Update songs',
]); ?>

<?php $this->section('content') ?>
    <div class="grid-x grid-padding-x margin-y">
        <div class="small-12 cell">
            <form action="<?= $this->pathFor('admin_songs_update_post') ?>" method="post">
                <?= $this->insert('martynbiz-core::partials/csrf_fields.phtml') ?>
                <button class="button large"><?= $this->translate('update') ?></button>
            </form>
        </div>
    </div>
<?php $this->replace() ?>
