<?php $this->layout('layouts/console', [
    'title' => 'Playlist',
]); ?>

<?php $this->section('content') ?>
    <div class="grid-x grid-padding-x margin-top">
        <div class="small-12 cell">
            <form action="<?= $this->pathFor('console_playlists_delete_song') ?>" method="post" id="playlist-form">
                <input type="hidden" name="_METHOD" value="DELETE"/>
                <input type="hidden" name="<?= $this->csrf_name ?>" value="<?= $this->csrf_value ?>">
                <input type="hidden" name="song_id" value="<?= $this->song->id ?>">

                <p><?= sprintf($this->translate('are_you_sure_you_want_to_remove__song__'), $this->song->name) ?></p>

                <button class="button large"><?= $this->translate('remove_song') ?></button>
            </form>
        </div>
    </div>
<?php $this->replace() ?>
