<?php $this->layout('layouts/console', [
    'title' => 'Artists',
    'back_path' => $this->pathFor('console_home'),
]); ?>

<?php $this->section('content') ?>
    <div class="grid-x grid-padding-x margin-bottom">
        <div class="small-12 cell">
            <nav aria-label="You are here:" role="navigation">
                <ul class="breadcrumbs">
                    <li><a href="<?= $this->pathFor('console_home') ?>"><?= $this->translate('home') ?></a></li>
                    <li>
                        <span class="show-for-sr">Current: </span> <?= $this->translate('languages') ?>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="grid-x grid-padding-x margin-bottom languages-list">
        <?php foreach ($this->languages as $language): ?>
            <div class="small-4 cell languages-list__item">
                <a href="<?= $this->pathFor('console_languages_view', ['language_id' => $language->id]); ?>" class="button expanded large"><?= $language->name ?></a>
            </div>
        <?php endforeach ?>
    </div>
<?php $this->replace() ?>
