<?php
$currentPage = $this->page;
$totalPages = $this->total_pages;

// this is the limit of numbers on either side of current page
$leftRight = 3;

$pageStart = 1;
if (($currentPage - $leftRight) > $pageStart) $pageStart = $currentPage - $leftRight;

$pageEnd = $this->total_pages;
if (($currentPage + $leftRight) < $pageEnd) $pageEnd = $currentPage + $leftRight;
?>
<?php if ($totalPages > 1): ?>
<div class="grid-x grid-padding-x margin-y">
    <div class="small-6 cell">
        <?php if ($currentPage > 1): ?>
            <a href="?<?= $this->generateQueryString(['page'=>($currentPage-1)]) ?>" class="button large" aria-label="Prev page"><?= $this->translate('pagination_previous') ?></a>
        <?php endif; ?>
    </div>
    <div class="small-6 cell text-right">
        <?php if ($currentPage < $totalPages): ?>
            <a href="?<?= $this->generateQueryString(['page'=>(++$currentPage)]) ?>" class="button large" aria-label="Next page"><?= $this->translate('pagination_next') ?></a>
        <?php endif; ?>
    </div>
</div>
<?php endif ?>
